name: tests
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest
    env:
        SESSION_KEY: 'secretkeysdfasdfasdfasdfasdfasdf'

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      # Ставим зависимости
      - name: npm install
        run: make install
      # Запускаем линтер
      - name: run linter
        run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name